@startmindmap
* Столик для подложек
** Магнитотранспортная система
*** Базовая основа для магнитной левитации
*** Система передвижения столика по осям X и Y
*** Система охлаждения
** Столик
*** Поворотный столик
*** Упор для подложки
*** Система охлаждения
** Интерферометры
@endmindmap