@startmindmap
* Столик для подложек
** Магнитотранспортная система
*** Стол для магнитной левитации
*** Система передвижения столика по осям X и Y
** Столик
*** Поворотный столик
*** Упор для подложки
*** Система охлаждения
** Интерферометры
@endmindmap